"""
evaluate_compressed.py — Evaluation for Compressed Models (Pruning, Quantization).

Specifically designed for models generated by compression_benchmark_local.py:
  • Handles .pth (baseline / quantized) and .pth.gz (sparse pruning)
  • Correctly counts non-zero parameters for both sparse and quantized models
  • Reconstructs quantized ResNet-18 architectures for PTQ/QAT
  • Benchmarks latency on CPU for quantized models and GPU/CPU for others

Baseline workflow:
  1. Evaluate baseline once and save:
       python evaluate_compressed.py --weights baseline.pth --save-json results/baseline.json
  2. Compare any compressed model against the frozen baseline:
       python evaluate_compressed.py --weights pruned.pth.gz --baseline-json results/baseline.json
     Or still evaluate a live baseline (old behaviour):
       python evaluate_compressed.py --weights pruned.pth.gz --baseline baseline.pth
"""

import argparse
import json
import os
import time
import gzip
import pickle
import types
import numpy as np
import torch
import torch.nn as nn
import random
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import classification_report, f1_score

# ── Reproducibility & Constants ───────────────────────────────────────────────
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
IMG_SIZE = 224
DATA_DIR = 'PlantVillage'
CLASSES_15 = [
    'Pepper__bell___Bacterial_spot', 'Pepper__bell___healthy',
    'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy',
    'Tomato_Bacterial_spot', 'Tomato_Early_blight', 'Tomato_Late_blight',
    'Tomato_Leaf_Mold', 'Tomato_Septoria_leaf_spot',
    'Tomato_Spider_mites_Two_spotted_spider_mite', 'Tomato__Target_Spot',
    'Tomato__Tomato_YellowLeaf__Curl_Virus', 'Tomato__Tomato_mosaic_virus',
    'Tomato_healthy',
]

# ── Quantization Helpers ──────────────────────────────────────────────────────

class QuantizableBasicBlock(nn.Module):
    expansion = 1
    def __init__(self, inplanes, planes, stride=1, downsample=None,
                 groups=1, base_width=64, dilation=1, norm_layer=None):
        super().__init__()
        if norm_layer is None: norm_layer = nn.BatchNorm2d
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=3, stride=stride,
                               padding=1, groups=groups, bias=False, dilation=dilation)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=1,
                               padding=1, groups=groups, bias=False, dilation=dilation)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride
        self.skip_add = torch.nn.quantized.FloatFunctional()

    def forward(self, x):
        identity = x
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        if self.downsample is not None:
            identity = self.downsample(x)
        out = self.skip_add.add(out, identity)
        out = self.relu(out)
        return out

def build_model(num_classes=15):
    model = models.resnet18(weights=None)
    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(p=0.3),
        nn.Linear(in_features, num_classes),
    )
    return model

def load_weights_into_quantizable(state_dict, num_classes=15):
    q_model = build_model(num_classes)
    try:
        q_model.load_state_dict(state_dict, strict=True)
    except:
        pass

    for layer_name in ['layer1', 'layer2', 'layer3', 'layer4']:
        layer = getattr(q_model, layer_name)
        for i in range(len(layer)):
            old = layer[i]
            nb = QuantizableBasicBlock(
                inplanes=old.conv1.in_channels,
                planes=old.conv1.out_channels,
                stride=old.stride,
                downsample=old.downsample,
            )
            nb.conv1.weight.data.copy_(old.conv1.weight.data)
            nb.bn1.weight.data.copy_(old.bn1.weight.data)
            nb.bn1.bias.data.copy_(old.bn1.bias.data)
            nb.bn1.running_mean.copy_(old.bn1.running_mean)
            nb.bn1.running_var.copy_(old.bn1.running_var)
            nb.conv2.weight.data.copy_(old.conv2.weight.data)
            nb.bn2.weight.data.copy_(old.bn2.weight.data)
            nb.bn2.bias.data.copy_(old.bn2.bias.data)
            nb.bn2.running_mean.copy_(old.bn2.running_mean)
            nb.bn2.running_var.copy_(old.bn2.running_var)
            layer[i] = nb
    return q_model

def fuse_resnet_modules(model):
    model.eval()
    torch.quantization.fuse_modules(model, ['conv1', 'bn1', 'relu'], inplace=True)
    for layer_name in ['layer1', 'layer2', 'layer3', 'layer4']:
        layer = getattr(model, layer_name)
        for block in layer:
            torch.quantization.fuse_modules(block, ['conv1', 'bn1', 'relu'], inplace=True)
            torch.quantization.fuse_modules(block, ['conv2', 'bn2'], inplace=True)
            if block.downsample is not None:
                torch.quantization.fuse_modules(block.downsample, ['0', '1'], inplace=True)
    return model

# ── Loading Logic ─────────────────────────────────────────────────────────────

def adapt_model_to_state_dict(model, state_dict):
    """Adapta a arquitetura do modelo FP32 para bater com os tensores reduzidos do state_dict"""
    def _replace_module(model, name, new_module):
        parts = name.split('.')
        parent = model
        for p in parts[:-1]:
            parent = getattr(parent, p)
        setattr(parent, parts[-1], new_module)

    for name, module in dict(model.named_modules()).items():
        if name == "": continue
        w_key = name + ".weight"
        if w_key in state_dict:
            state_shape = state_dict[w_key].shape
            
            if isinstance(module, nn.Conv2d):
                out_c, in_c_over_groups, kH, kW = state_shape
                in_c = in_c_over_groups * module.groups
                if module.in_channels != in_c or module.out_channels != out_c:
                    new_conv = nn.Conv2d(in_c, out_c, module.kernel_size, module.stride, 
                                         module.padding, bias=(module.bias is not None), 
                                         groups=module.groups)
                    _replace_module(model, name, new_conv)
            
            elif isinstance(module, nn.BatchNorm2d):
                num_f = state_shape[0]
                if module.num_features != num_f:
                    new_bn = nn.BatchNorm2d(num_f, module.eps, module.momentum, 
                                            module.affine, module.track_running_stats)
                    _replace_module(model, name, new_bn)
                    
            elif isinstance(module, nn.Linear):
                out_f, in_f = state_shape
                if module.in_features != in_f or module.out_features != out_f:
                    new_lin = nn.Linear(in_f, out_f, bias=(module.bias is not None))
                    _replace_module(model, name, new_lin)
    return model

def load_sparse(model, path, is_quantized=False):
    with gzip.open(path, 'rb') as f:
        payload = pickle.load(f)

    if isinstance(payload, nn.Module):
        print("  Detected: full model object in .gz — using directly.")
        return payload.eval()

    if not isinstance(payload, dict):
        raise TypeError(f"Unexpected payload type in .gz: {type(payload)}")

    dense_state = {
        k: (v.to_dense() if isinstance(v, torch.Tensor) and v.is_sparse else v)
        for k, v in payload.items()
    }

    if not is_quantized:
        model = adapt_model_to_state_dict(model, dense_state)
        model.load_state_dict(dense_state, strict=True)
        return model

    has_quantized_conv = any(
        isinstance(v, torch.Tensor) and v.is_quantized
        for v in dense_state.values()
    )
    has_packed = any('_packed_params' in k for k in dense_state)

    if has_quantized_conv:
        print("  Detected: static PTQ (FX) — quantized Conv2d weights found.")
        try:
            return load_static_ptq_fx(dense_state, num_classes=15)
        except Exception as e:
            raise RuntimeError(f"Failed to reconstruct static PTQ (FX) model: {e}")

    elif has_packed:
        print("  Detected: dynamic PTQ — quantized Linear only.")
        model = torch.quantization.quantize_dynamic(
            model, {nn.Linear}, dtype=torch.qint8
        )
        own_state = model.state_dict()
        for k, v in dense_state.items():
            if k in own_state:
                own_state[k] = v
        model.load_state_dict(own_state, strict=False)
        return model

    else:
        model.load_state_dict(dense_state, strict=True)
        return model
        
def load_static_ptq_fx(dense_state, num_classes=15):
    from torch.ao.quantization.quantize_fx import prepare_fx, convert_fx
    from torch.ao.quantization import QConfigMapping
    import torch.ao.nn.quantized as nnq
    import torch.ao.nn.intrinsic.quantized as nniq

    model = build_model(num_classes).eval()
    qconfig_mapping = QConfigMapping().set_global(
        torch.ao.quantization.get_default_qconfig('fbgemm')
    )
    example_input = torch.randn(1, 3, 224, 224)
    model_prepared = prepare_fx(model, qconfig_mapping, example_input)
    model_converted = convert_fx(model_prepared)

    module_keys     = {k: v for k, v in dense_state.items() if '.' in k}
    activation_keys = {k: v for k, v in dense_state.items() if '.' not in k}

    converted_state = model_converted.state_dict()
    matched, missed = 0, 0
    for k, v in activation_keys.items():
        if k in converted_state:
            converted_state[k] = v
            matched += 1
        else:
            missed += 1
    print(f"  Activation scales: {matched} matched, {missed} missed")
    model_converted.load_state_dict(converted_state, strict=False)

    for mod_name, mod in model_converted.named_modules():

        if isinstance(mod, (nnq.Conv2d, nniq.ConvReLU2d)):
            w_key  = f"{mod_name}.weight"
            sc_key = f"{mod_name}.scale"
            zp_key = f"{mod_name}.zero_point"
            b_key  = f"{mod_name}.bias"

            if w_key in module_keys:
                mod.set_weight_bias(module_keys[w_key], module_keys.get(b_key))
                mod.scale      = float(module_keys[sc_key])
                mod.zero_point = int(module_keys[zp_key])
                print(f"    [{type(mod).__name__}] loaded: {mod_name}")

        elif isinstance(mod, (nnq.Linear, nniq.LinearReLU)):
            pp_key = f"{mod_name}._packed_params._packed_params"
            sc_key = f"{mod_name}.scale"
            zp_key = f"{mod_name}.zero_point"

            if pp_key in module_keys:
                w_q, b_f = module_keys[pp_key]
                mod.set_weight_bias(w_q, b_f)
                if sc_key in module_keys:
                    mod.scale      = float(module_keys[sc_key])
                    mod.zero_point = int(module_keys[zp_key])
                print(f"    [{type(mod).__name__}] loaded: {mod_name}")

    scales = [mod.scale for _, mod in model_converted.named_modules()
              if hasattr(mod, 'scale') and isinstance(mod.scale, float)]
    unique = set(round(s, 6) for s in scales)
    print(f"  Output scales únicas (sample): {sorted(unique)[:5]}")
    if unique == {1.0}:
        print("  ⚠️  AVISO: todas as scales ainda são 1.0 — restauração falhou!")

    return model_converted.eval()
    
def load_any_model(path, is_quantized=False, num_classes=15, device='cpu'):
    model = build_model(num_classes)

    if path.endswith('.gz'):
        print(f"Loading sparse model from {path}...")
        model = load_sparse(model, path, is_quantized=is_quantized)
    else:
        state = torch.load(path, map_location='cpu', weights_only=False)
        if is_quantized:
            print(f"Reconstructing quantized model from {path}...")

            has_quantized_conv = any(
                'conv1._packed_params' in k or 'conv1.bias' in k
                for k in state.keys()
            )
            is_dynamic = not has_quantized_conv

            if is_dynamic:
                print("  Detected: Dynamic quantization (Linear only)")
                model = torch.quantization.quantize_dynamic(
                    model, {nn.Linear}, dtype=torch.qint8
                )
                model.load_state_dict(state, strict=False)
            else:
                print("  Detected: Static PTQ / QAT")
                model = load_weights_into_quantizable(state, num_classes)
                fuse_resnet_modules(model)
                model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
                model.quant = torch.quantization.QuantStub()
                model.dequant = torch.quantization.DeQuantStub()
                
                def _forward_impl_quantized(self, x):
                    x = self.quant(x)
                    x = self.conv1(x)
                    x = self.bn1(x)
                    x = self.relu(x)
                    x = self.maxpool(x)
                    x = self.layer1(x)
                    x = self.layer2(x)
                    x = self.layer3(x)
                    x = self.layer4(x)
                    x = self.avgpool(x)
                    x = torch.flatten(x, 1)
                    x = self.fc(x)
                    x = self.dequant(x)
                    return x
                
                model._forward_impl = types.MethodType(_forward_impl_quantized, model)

                torch.quantization.prepare(model, inplace=True)
                torch.quantization.convert(model, inplace=True)
                
                current_model_state = model.state_dict()
                for k, v in current_model_state.items():
                    if k not in state:
                        state[k] = v
                
                model.load_state_dict(state, strict=False)
        else:
            print(f"Loading standard model from {path}...")
            model = adapt_model_to_state_dict(model, state)
            model.load_state_dict(state)

    model = model.to(device)
    model.eval()
    return model
    
# ── Metrics ───────────────────────────────────────────────────────────────────

def count_nonzero_params(model):
    total, nonzero = 0, 0
    quantized_types = (
        torch.nn.quantized.Conv2d, torch.nn.quantized.Linear,
        torch.nn.intrinsic.quantized.ConvReLU2d, torch.nn.intrinsic.quantized.LinearReLU,
    )

    for name, mod in model.named_modules():
        if isinstance(mod, quantized_types):
            try:
                w = mod.weight()
                data = w.int_repr().float()
                total += data.numel()
                nonzero += int((data != 0).sum().item())
                if hasattr(mod, 'bias') and mod.bias() is not None:
                    b = mod.bias().float()
                    total += b.numel()
                    nonzero += int((b != 0).sum().item())
            except: pass
        elif isinstance(mod, (nn.Conv2d, nn.Linear)):
            if hasattr(mod, 'weight'):
                data = mod.weight.data
                total += data.numel()
                nonzero += int((data != 0).sum().item())
            if hasattr(mod, 'bias') and mod.bias is not None:
                data = mod.bias.data
                total += data.numel()
                nonzero += int((data != 0).sum().item())

    return total, nonzero

def compute_macs(model, input_shape, device):
    macs = [0]
    def conv_hook(m, _inp, out):
        _, _, h, w = out.shape
        k_w, k_h = m.kernel_size if isinstance(m.kernel_size, tuple) else (m.kernel_size, m.kernel_size)
        kops = k_w * k_h
        macs[0] += (m.in_channels // m.groups) * kops * m.out_channels * h * w
        
    def linear_hook(m, _inp, _out):
        macs[0] += m.in_features * m.out_features

    handles = []
    for module in model.modules():
        if isinstance(module, nn.Conv2d) or 'Conv2d' in str(type(module)):
             handles.append(module.register_forward_hook(conv_hook))
        elif isinstance(module, nn.Linear) or 'Linear' in str(type(module)):
             handles.append(module.register_forward_hook(linear_hook))

    model.eval()
    with torch.no_grad():
        x = torch.zeros(1, *input_shape, device=device)
        model(x)

    for h in handles:
        h.remove()
    return macs[0]

def theoretical_size_mb(num_params, bytes_per_param):
    return num_params * bytes_per_param / 1024**2

def benchmark_latency(model, device, batch_size, n_runs=500, warmup=20):
    model.eval().to(device)
    x = torch.randn(batch_size, 3, IMG_SIZE, IMG_SIZE, device=device)
    
    with torch.no_grad():
        for _ in range(warmup):
            _ = model(x)
            
    if device.type == 'cuda':
        torch.cuda.synchronize()

    times = []
    with torch.no_grad():
        for _ in range(n_runs):
            if device.type == 'cuda':
                start_event = torch.cuda.Event(enable_timing=True)
                end_event = torch.cuda.Event(enable_timing=True)
                start_event.record()
                _ = model(x)
                end_event.record()
                torch.cuda.synchronize()
                times.append(start_event.elapsed_time(end_event))
            else:
                t0 = time.perf_counter()
                _ = model(x)
                times.append((time.perf_counter() - t0) * 1000.0)

    times = np.array(times)
    p5, p95 = np.percentile(times, [5, 95])
    filtered_times = times[(times >= p5) & (times <= p95)]
    
    if len(filtered_times) == 0:
        filtered_times = times

    return {
        "mean_ms":         float(filtered_times.mean()),
        "std_ms":          float(filtered_times.std()),
        "p50_ms":          float(np.percentile(times, 50)),
        "p95_ms":          float(np.percentile(times, 95)),
        "p99_ms":          float(np.percentile(times, 99)),
        "throughput_imgs": float(batch_size * 1000.0 / filtered_times.mean()),
    }
    
@torch.no_grad()
def evaluate_accuracy(model, loader, device):
    model.eval().to(device)
    all_preds, all_labels = [], []
    for imgs, lbls in loader:
        imgs = imgs.to(device)
        logits = model(imgs)
        preds = logits.argmax(1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(lbls.numpy())
    return np.array(all_preds), np.array(all_labels)

def full_evaluation(arch, weights_path, model, loader, device, classes, batch_sizes=[1, 32], n_runs=500):
    total, nonzero = count_nonzero_params(model)
    buffers = sum(b.numel() for b in model.buffers())
    macs = compute_macs(model, (3, IMG_SIZE, IMG_SIZE), device)

    latencies = {
        str(bs): benchmark_latency(model, device, bs, n_runs=500)
        for bs in batch_sizes
    }

    preds, labels = evaluate_accuracy(model, loader, device)
    top1 = float((preds == labels).mean())
    f1_macro = float(f1_score(labels, preds, average="macro"))
    f1_weighted = float(f1_score(labels, preds, average="weighted"))
    per_class = classification_report(labels, preds, target_names=classes, digits=4)

    return {
        "arch": arch,
        "weights": weights_path,
        "params_total": total,
        "params_trainable": 0,
        "buffers": buffers,
        "macs": macs,
        "flops": macs * 2,
        "file_size_mb": os.path.getsize(weights_path) / 1024**2,
        "fp32_size_mb": theoretical_size_mb(total, 4),
        "fp16_size_mb": theoretical_size_mb(total, 2),
        "int8_size_mb": theoretical_size_mb(total, 1),
        "latencies": latencies,
        "top1": top1,
        "f1_macro": f1_macro,
        "f1_weighted": f1_weighted,
        "per_class_report": per_class,
        "preds": preds,
        "labels": labels,
        "nonzero_params": nonzero
    }

# ── Data Loading ──────────────────────────────────────────────────────────────

eval_tf = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

class TransformSubset(torch.utils.data.Dataset):
    def __init__(self, dataset, indices, transform):
        self.dataset = dataset
        self.indices = indices
        self.transform = transform
    def __len__(self): return len(self.indices)
    def __getitem__(self, i):
        img, label = self.dataset[self.indices[i]]
        return self.transform(img), label

def get_test_loader():
    full_dataset = datasets.ImageFolder(DATA_DIR)
    all_classes = full_dataset.classes
    valid_class_idx = {all_classes.index(c): new_i for new_i, c in enumerate(CLASSES_15) if c in all_classes}
    filtered_samples = [(path, valid_class_idx[lbl]) for path, lbl in full_dataset.samples if lbl in valid_class_idx]
    full_dataset.samples = filtered_samples
    full_dataset.targets = [lbl for _, lbl in filtered_samples]

    labels = np.array(full_dataset.targets)
    sss1 = StratifiedShuffleSplit(n_splits=1, test_size=0.15, random_state=SEED)
    _, test_idx = next(sss1.split(np.zeros(len(labels)), labels))

    test_ds = TransformSubset(full_dataset, test_idx, eval_tf)
    return DataLoader(test_ds, batch_size=64, shuffle=False, num_workers=4)

# ── Main ──────────────────────────────────────────────────────────────────────

def _strip_for_json(r):
    """Remove arrays numpy que não são serializáveis em JSON."""
    return {k: v for k, v in r.items() if k not in ("preds", "labels")}

def _load_baseline_from_json(path):
    """
    Carrega resultados do baseline a partir de um JSON salvo anteriormente.
    Retorna um dict com as mesmas chaves que full_evaluation() produz,
    exceto 'preds' e 'labels' (que não são gravados no JSON).
    """
    print(f"\nLoading frozen baseline results from {path}...")
    with open(path, 'r') as f:
        data = json.load(f)

    # Suporta tanto {"target": {...}} quanto o dict direto
    if "target" in data and isinstance(data["target"], dict):
        results = data["target"]
    elif "baseline" in data and isinstance(data["baseline"], dict):
        results = data["baseline"]
    else:
        results = data

    print(f"  Baseline weights:  {results.get('weights', 'unknown')}")
    print(f"  Baseline accuracy: {results.get('top1', float('nan'))*100:.2f}%")
    return results

def main():
    parser = argparse.ArgumentParser(
        description="Evaluate compressed models against a (optionally frozen) baseline."
    )
    parser.add_argument("--weights", type=str, required=True,
                        help="Compressed model to evaluate (.pth or .pth.gz).")
    parser.add_argument("--quantized", action="store_true",
                        help="Flag the target model as quantized.")
    parser.add_argument("--baseline", type=str, default=None,
                        help="Path to baseline .pth — evaluates it live. "
                             "Ignored when --baseline-json is provided.")
    parser.add_argument("--baseline-json", type=str, default=None,
                        help="Path to a previously saved baseline JSON. "
                             "Skips re-evaluation and uses frozen metrics instead. "
                             "Takes priority over --baseline.")
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--save-json", type=str, default=None,
                        help="Where to save the JSON report for this run.")
    args = parser.parse_args()

    if args.device:
        device = torch.device(args.device)
    else:
        device = torch.device('cuda' if torch.cuda.is_available() and not args.quantized else 'cpu')

    print(f"Using device: {device}")

    loader = get_test_loader()

    # ── Evaluate target model ─────────────────────────────────────────────────
    target_model = load_any_model(args.weights, is_quantized=args.quantized, device=device)

    print("\nEvaluating target model...")
    target_results = full_evaluation("resnet18", args.weights, target_model, loader, device, CLASSES_15)

    t_acc = target_results["top1"]
    t_size = target_results["file_size_mb"]
    t_latency = target_results["latencies"]["1"]["mean_ms"]
    t_total = target_results["params_total"]
    t_nz = target_results["nonzero_params"]

    print(f"\n{'='*40}")
    print(f" TARGET MODEL: {os.path.basename(args.weights)}")
    print(f"{'='*40}")
    print(f" Accuracy:          {t_acc*100:.2f}%")
    print(f" Size on disk:      {t_size:.2f} MB")
    print(f" Latency (batch=1): {t_latency:.2f} ms")
    print(f" Total Params:      {t_total:,}")
    print(f" Non-zero Params:   {t_nz:,}")
    print(f" Sparsity:          {100*(1-t_nz/t_total):.1f}%")

    # ── Baseline: frozen JSON (preferred) or live evaluation ─────────────────
    baseline_results = None

    if args.baseline_json:
        # ── FROZEN BASELINE — no model load, no re-evaluation ────────────────
        baseline_results = _load_baseline_from_json(args.baseline_json)

        b_acc     = baseline_results.get("top1", float("nan"))
        b_size    = baseline_results.get("file_size_mb", float("nan"))
        b_latency = baseline_results.get("latencies", {}).get("1", {}).get("mean_ms", float("nan"))

        print(f"\n{'='*40}")
        print(f" COMPARISON (Target vs Frozen Baseline)")
        print(f"{'='*40}")
        print(f" Accuracy Delta:    {100*(t_acc - b_acc):+.2f} pp")
        print(f" Compression Ratio: {b_size/t_size:.2f}x" if t_size else " Compression Ratio: N/A")
        print(f" Speedup:           {b_latency/t_latency:.2f}x" if t_latency else " Speedup: N/A")
        # Agreement not available without frozen preds — skip gracefully
        print(f" (Prediction agreement not available from frozen JSON)")

    elif args.baseline:
        # ── LIVE BASELINE — old behaviour, kept for compatibility ─────────────
        print("\nEvaluating baseline model (live)...")
        base_model = load_any_model(args.baseline, is_quantized=False, device=device)
        baseline_results = full_evaluation("resnet18", args.baseline, base_model, loader, device, CLASSES_15)

        b_acc     = baseline_results["top1"]
        b_size    = baseline_results["file_size_mb"]
        b_latency = baseline_results["latencies"]["1"]["mean_ms"]

        print(f"\n{'='*40}")
        print(f" COMPARISON (Target vs Baseline)")
        print(f"{'='*40}")
        print(f" Accuracy Delta:    {100*(t_acc - b_acc):+.2f} pp")
        print(f" Compression Ratio: {b_size/t_size:.2f}x")
        print(f" Speedup:           {b_latency/t_latency:.2f}x")

        agreement = (target_results["preds"] == baseline_results["preds"]).mean()
        print(f" Agreement:         {100*agreement:.2f}%")

    print("\nDetailed Classification Report (Target):")
    print(target_results["per_class_report"])

    # ── Save JSON ─────────────────────────────────────────────────────────────
    if args.save_json:
        payload = {"target": _strip_for_json(target_results)}
        if baseline_results:
            # Se veio de JSON frozen, já está limpo; se veio live, strip numpy
            if args.baseline_json:
                payload["baseline"] = baseline_results
            else:
                payload["baseline"] = _strip_for_json(baseline_results)

        os.makedirs(os.path.dirname(args.save_json) or '.', exist_ok=True)
        with open(args.save_json, 'w') as f:
            json.dump(payload, f, indent=2)
        print(f"\nJSON report saved to: {args.save_json}")

if __name__ == "__main__":
    main()