"""
evaluate_compressed.py — Evaluation for Compressed Models (Pruning, Quantization).

Specifically designed for models generated by compression_benchmark_local.py:
  • Handles .pth (baseline / quantized) and .pth.gz (sparse pruning)
  • Correctly counts non-zero parameters for both sparse and quantized models
  • Reconstructs quantized ResNet-18 architectures for PTQ/QAT
  • Benchmarks latency on CPU for quantized models and GPU/CPU for others
"""

import argparse
import json
import os
import time
import gzip
import pickle
import types
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import classification_report, f1_score

# ── Reproducibility & Constants ───────────────────────────────────────────────
SEED = 42
IMG_SIZE = 224
DATA_DIR = 'PlantVillage'
CLASSES_15 = [
    'Pepper__bell___Bacterial_spot', 'Pepper__bell___healthy',
    'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy',
    'Tomato_Bacterial_spot', 'Tomato_Early_blight', 'Tomato_Late_blight',
    'Tomato_Leaf_Mold', 'Tomato_Septoria_leaf_spot',
    'Tomato_Spider_mites_Two_spotted_spider_mite', 'Tomato__Target_Spot',
    'Tomato__Tomato_YellowLeaf__Curl_Virus', 'Tomato__Tomato_mosaic_virus',
    'Tomato_healthy',
]

# ── Quantization Helpers ──────────────────────────────────────────────────────

class QuantizableBasicBlock(nn.Module):
    expansion = 1
    def __init__(self, inplanes, planes, stride=1, downsample=None,
                 groups=1, base_width=64, dilation=1, norm_layer=None):
        super().__init__()
        if norm_layer is None: norm_layer = nn.BatchNorm2d
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=3, stride=stride,
                               padding=1, groups=groups, bias=False, dilation=dilation)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=1,
                               padding=1, groups=groups, bias=False, dilation=dilation)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride
        self.skip_add = torch.nn.quantized.FloatFunctional()

    def forward(self, x):
        identity = x
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        if self.downsample is not None:
            identity = self.downsample(x)
        out = self.skip_add.add(out, identity)
        out = self.relu(out)
        return out

def build_model(num_classes=15):
    model = models.resnet18(weights=None)
    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(p=0.3),
        nn.Linear(in_features, num_classes),
    )
    return model

def load_weights_into_quantizable(state_dict, num_classes=15):
    q_model = build_model(num_classes)
    try:
        q_model.load_state_dict(state_dict, strict=True)
    except:
        pass

    for layer_name in ['layer1', 'layer2', 'layer3', 'layer4']:
        layer = getattr(q_model, layer_name)
        for i in range(len(layer)):
            old = layer[i]
            nb = QuantizableBasicBlock(
                inplanes=old.conv1.in_channels,
                planes=old.conv1.out_channels,
                stride=old.stride,
                downsample=old.downsample,
            )
            nb.conv1.weight.data.copy_(old.conv1.weight.data)
            nb.bn1.weight.data.copy_(old.bn1.weight.data)
            nb.bn1.bias.data.copy_(old.bn1.bias.data)
            nb.bn1.running_mean.copy_(old.bn1.running_mean)
            nb.bn1.running_var.copy_(old.bn1.running_var)
            nb.conv2.weight.data.copy_(old.conv2.weight.data)
            nb.bn2.weight.data.copy_(old.bn2.weight.data)
            nb.bn2.bias.data.copy_(old.bn2.bias.data)
            nb.bn2.running_mean.copy_(old.bn2.running_mean)
            nb.bn2.running_var.copy_(old.bn2.running_var)
            layer[i] = nb
    return q_model

def fuse_resnet_modules(model):
    model.eval()
    torch.quantization.fuse_modules(model, ['conv1', 'bn1', 'relu'], inplace=True)
    for layer_name in ['layer1', 'layer2', 'layer3', 'layer4']:
        layer = getattr(model, layer_name)
        for block in layer:
            torch.quantization.fuse_modules(block, ['conv1', 'bn1', 'relu'], inplace=True)
            torch.quantization.fuse_modules(block, ['conv2', 'bn2'], inplace=True)
            if block.downsample is not None:
                torch.quantization.fuse_modules(block.downsample, ['0', '1'], inplace=True)
    return model

# ── Loading Logic ─────────────────────────────────────────────────────────────

def load_sparse(model, path):
    with gzip.open(path, 'rb') as f:
        sparse_state = pickle.load(f)
    dense_state = {k: v.to_dense() if hasattr(v, 'is_sparse') and v.is_sparse else v
                   for k, v in sparse_state.items()}
    model.load_state_dict(dense_state)
    return model

def load_any_model(path, is_quantized=False, num_classes=15, device='cpu'):
    model = build_model(num_classes)

    if path.endswith('.gz'):
        print(f"Loading sparse model from {path}...")
        model = load_sparse(model, path)
    else:
        state = torch.load(path, map_location='cpu', weights_only=False)
        if is_quantized:
            print(f"Reconstructing quantized model from {path}...")

            has_quantized_conv = any(
                'conv1._packed_params' in k or 'conv1.bias' in k
                for k in state.keys()
            )
            is_dynamic = not has_quantized_conv

            if is_dynamic:
                print("  Detected: Dynamic quantization (Linear only)")
                model = torch.quantization.quantize_dynamic(
                    model, {nn.Linear}, dtype=torch.qint8
                )
                model.load_state_dict(state, strict=False)
            else:
                print("  Detected: Static PTQ / QAT")
                model = load_weights_into_quantizable(state, num_classes)
                fuse_resnet_modules(model)
                model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
                model.quant = torch.quantization.QuantStub()
                model.dequant = torch.quantization.DeQuantStub()
                
                # --- CORREÇÃO: Injetar QuantStub no forward ---
                # Isso converte tensores float "CPU" para "QuantizedCPU"
                def _forward_impl_quantized(self, x):
                    x = self.quant(x)
                    x = self.conv1(x)
                    x = self.bn1(x)
                    x = self.relu(x)
                    x = self.maxpool(x)
                    x = self.layer1(x)
                    x = self.layer2(x)
                    x = self.layer3(x)
                    x = self.layer4(x)
                    x = self.avgpool(x)
                    x = torch.flatten(x, 1)
                    x = self.fc(x)
                    x = self.dequant(x)
                    return x
                
                model._forward_impl = types.MethodType(_forward_impl_quantized, model)
                # ----------------------------------------------

                torch.quantization.prepare(model, inplace=True)
                torch.quantization.convert(model, inplace=True)
                
                # Injeta default scale/zero_point para evitar erro KeyError da skip_add
                current_model_state = model.state_dict()
                for k, v in current_model_state.items():
                    if k not in state:
                        state[k] = v
                
                model.load_state_dict(state, strict=False)
        else:
            print(f"Loading standard model from {path}...")
            model.load_state_dict(state)

    model = model.to(device)
    model.eval()
    return model
    
# ── Metrics ───────────────────────────────────────────────────────────────────

def count_nonzero_params(model):
    total, nonzero = 0, 0
    quantized_types = (
        torch.nn.quantized.Conv2d, torch.nn.quantized.Linear,
        torch.nn.intrinsic.quantized.ConvReLU2d, torch.nn.intrinsic.quantized.LinearReLU,
    )

    for name, mod in model.named_modules():
        if isinstance(mod, quantized_types):
            try:
                w = mod.weight()
                data = w.int_repr().float()
                total += data.numel()
                nonzero += int((data != 0).sum().item())
                if hasattr(mod, 'bias') and mod.bias() is not None:
                    b = mod.bias().float()
                    total += b.numel()
                    nonzero += int((b != 0).sum().item())
            except: pass
        elif isinstance(mod, (nn.Conv2d, nn.Linear)):
            if hasattr(mod, 'weight'):
                data = mod.weight.data
                total += data.numel()
                nonzero += int((data != 0).sum().item())
            if hasattr(mod, 'bias') and mod.bias is not None:
                data = mod.bias.data
                total += data.numel()
                nonzero += int((data != 0).sum().item())

    return total, nonzero

def compute_macs(model, input_shape, device):
    macs = [0]
    def conv_hook(m, _inp, out):
        _, _, h, w = out.shape
        # Captura informações mesmo com tensores quantizados
        k_w, k_h = m.kernel_size if isinstance(m.kernel_size, tuple) else (m.kernel_size, m.kernel_size)
        kops = k_w * k_h
        macs[0] += (m.in_channels // m.groups) * kops * m.out_channels * h * w
        
    def linear_hook(m, _inp, _out):
        macs[0] += m.in_features * m.out_features

    handles = []
    for module in model.modules():
        if isinstance(module, nn.Conv2d) or 'Conv2d' in str(type(module)):
             handles.append(module.register_forward_hook(conv_hook))
        elif isinstance(module, nn.Linear) or 'Linear' in str(type(module)):
             handles.append(module.register_forward_hook(linear_hook))

    model.eval()
    with torch.no_grad():
        x = torch.zeros(1, *input_shape, device=device)
        model(x)

    for h in handles:
        h.remove()
    return macs[0]

def theoretical_size_mb(num_params, bytes_per_param):
    return num_params * bytes_per_param / 1024**2

def benchmark_latency(model, device, batch_size, n_runs=50, warmup=10):
    model.eval().to(device)
    x = torch.randn(batch_size, 3, IMG_SIZE, IMG_SIZE, device=device)
    times = []
    with torch.no_grad():
        for _ in range(warmup):
            y = model(x); float(y.flatten()[0])
        for _ in range(n_runs):
            t0 = time.perf_counter()
            y = model(x); float(y.flatten()[0])
            times.append((time.perf_counter() - t0) * 1000.0)
    times = np.array(times)
    return {
        "mean_ms":         float(times.mean()),
        "std_ms":          float(times.std()),
        "p50_ms":          float(np.percentile(times, 50)),
        "p95_ms":          float(np.percentile(times, 95)),
        "p99_ms":          float(np.percentile(times, 99)),
        "throughput_imgs": float(batch_size * 1000.0 / times.mean()),
    }

@torch.no_grad()
def evaluate_accuracy(model, loader, device):
    model.eval().to(device)
    all_preds, all_labels = [], []
    for imgs, lbls in loader:
        imgs = imgs.to(device)
        logits = model(imgs)
        preds = logits.argmax(1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(lbls.numpy())
    return np.array(all_preds), np.array(all_labels)

def full_evaluation(arch, weights_path, model, loader, device, classes, batch_sizes=[1, 32], n_runs=50):
    total, nonzero = count_nonzero_params(model)
    buffers = sum(b.numel() for b in model.buffers())
    macs = compute_macs(model, (3, IMG_SIZE, IMG_SIZE), device)

    latencies = {
        str(bs): benchmark_latency(model, device, bs, n_runs=n_runs)
        for bs in batch_sizes
    }

    preds, labels = evaluate_accuracy(model, loader, device)
    top1 = float((preds == labels).mean())
    f1_macro = float(f1_score(labels, preds, average="macro"))
    f1_weighted = float(f1_score(labels, preds, average="weighted"))
    per_class = classification_report(labels, preds, target_names=classes, digits=4)

    return {
        "arch": arch,
        "weights": weights_path,
        "params_total": total,
        "params_trainable": 0,
        "buffers": buffers,
        "macs": macs,
        "flops": macs * 2,
        "file_size_mb": os.path.getsize(weights_path) / 1024**2,
        "fp32_size_mb": theoretical_size_mb(total, 4),
        "fp16_size_mb": theoretical_size_mb(total, 2),
        "int8_size_mb": theoretical_size_mb(total, 1),
        "latencies": latencies,
        "top1": top1,
        "f1_macro": f1_macro,
        "f1_weighted": f1_weighted,
        "per_class_report": per_class,
        "preds": preds,
        "labels": labels,
        "nonzero_params": nonzero
    }

# ── Data Loading ──────────────────────────────────────────────────────────────

eval_tf = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(IMG_SIZE),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

class TransformSubset(torch.utils.data.Dataset):
    def __init__(self, dataset, indices, transform):
        self.dataset = dataset
        self.indices = indices
        self.transform = transform
    def __len__(self): return len(self.indices)
    def __getitem__(self, i):
        img, label = self.dataset[self.indices[i]]
        return self.transform(img), label

def get_test_loader():
    full_dataset = datasets.ImageFolder(DATA_DIR)
    all_classes = full_dataset.classes
    valid_class_idx = {all_classes.index(c): new_i for new_i, c in enumerate(CLASSES_15) if c in all_classes}
    filtered_samples = [(path, valid_class_idx[lbl]) for path, lbl in full_dataset.samples if lbl in valid_class_idx]
    full_dataset.samples = filtered_samples
    full_dataset.targets = [lbl for _, lbl in filtered_samples]

    labels = np.array(full_dataset.targets)
    sss1 = StratifiedShuffleSplit(n_splits=1, test_size=0.15, random_state=SEED)
    _, test_idx = next(sss1.split(np.zeros(len(labels)), labels))

    test_ds = TransformSubset(full_dataset, test_idx, eval_tf)
    return DataLoader(test_ds, batch_size=64, shuffle=False, num_workers=4)

# ── Main ──────────────────────────────────────────────────────────────────────

def _strip_for_json(r):
    return {k: v for k, v in r.items() if k not in ("preds", "labels")}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--weights", type=str, required=True)
    parser.add_argument("--quantized", action="store_true")
    parser.add_argument("--baseline", type=str, default=None)
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--save-json", type=str, default=None)
    args = parser.parse_args()

    if args.device:
        device = torch.device(args.device)
    else:
        device = torch.device('cuda' if torch.cuda.is_available() and not args.quantized else 'cpu')

    print(f"Using device: {device}")

    loader = get_test_loader()

    # Load target model
    target_model = load_any_model(args.weights, is_quantized=args.quantized, device=device)

    print("\nEvaluating target model...")
    target_results = full_evaluation("resnet18", args.weights, target_model, loader, device, CLASSES_15)

    t_acc = target_results["top1"]
    t_size = target_results["file_size_mb"]
    t_latency = target_results["latencies"]["1"]["mean_ms"]
    t_total = target_results["params_total"]
    t_nz = target_results["nonzero_params"]

    print(f"\n{'='*40}")
    print(f" TARGET MODEL: {os.path.basename(args.weights)}")
    print(f"{'='*40}")
    print(f" Accuracy:          {t_acc*100:.2f}%")
    print(f" Size on disk:      {t_size:.2f} MB")
    print(f" Latency (batch=1): {t_latency:.2f} ms")
    print(f" Total Params:      {t_total:,}")
    print(f" Non-zero Params:   {t_nz:,}")
    print(f" Sparsity:          {100*(1-t_nz/t_total):.1f}%")

    baseline_results = None
    if args.baseline:
        print("\nEvaluating baseline model...")
        base_model = load_any_model(args.baseline, is_quantized=False, device=device)
        baseline_results = full_evaluation("resnet18", args.baseline, base_model, loader, device, CLASSES_15)

        b_acc = baseline_results["top1"]
        b_size = baseline_results["file_size_mb"]
        b_latency = baseline_results["latencies"]["1"]["mean_ms"]

        print(f"\n{'='*40}")
        print(f" COMPARISON (Target vs Baseline)")
        print(f"{'='*40}")
        print(f" Accuracy Delta:    {100*(t_acc - b_acc):+.2f} pp")
        print(f" Compression Ratio: {b_size/t_size:.2f}x")
        print(f" Speedup:           {b_latency/t_latency:.2f}x")

        agreement = (target_results["preds"] == baseline_results["preds"]).mean()
        print(f" Agreement:         {100*agreement:.2f}%")

    print("\nDetailed Classification Report (Target):")
    print(target_results["per_class_report"])

    if args.save_json:
        payload = {"target": _strip_for_json(target_results)}
        if baseline_results:
            payload["baseline"] = _strip_for_json(baseline_results)

        os.makedirs(os.path.dirname(args.save_json) or '.', exist_ok=True)
        with open(args.save_json, 'w') as f:
            json.dump(payload, f, indent=2)
        print(f"\nJSON report saved to: {args.save_json}")

if __name__ == "__main__":
    main()